server:
  port: 8888

# Config server: this will be used by other services. It is the main configuration service.
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
